#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv

def config_changed():
    """ Our workers dont have any config. The information it needs
     (master address) is delivered to the worker via the relation """
    pass

if __name__ == "__main__":
    config_changed()
