#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv

def install():
    hookenv.log('Installing charm: worker ')

if __name__ == "__main__":
    install()