#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv

def master_relation_joined():
    """ Pick up the remote unit address here"""
    relation_id = hookenv.relation_id()

    remoteUnit = os.environ.get('JUJU_REMOTE_UNIT', None) # remote_unit()

    masterAddr = hookenv.relation_get('private-address', unit=remoteUnit)

    hookenv.log(f"Joined with MASTER at private-address: {masterAddr}")

if __name__ == "__main__":
    master_relation_joined()
