#!/usr/bin/env python3

# https://charm-helpers.readthedocs.io/en/latest/
import os
import sys

sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))

from charmhelpers.core import (
    hookenv,
    host,
)


hooks = hookenv.Hooks()

config = hookenv.config()

log = hookenv.log

@hooks.hook('master-relation-changed')
def master_relation_changed():

    relation_id = hookenv.relation_id()

    if not hookenv.relation_get('master-enabled'):

        hookend.status_set("waiting", "Master not ready.")

    else:

        log(" ========= REL ========")
        
        msg = hookenv.relation_get('message')

        # Do something with the data ...
        
        hookenv.status_set("active", f"Master say: {msg}")
        
        # If we have a healthy relation, let the relation know.
        if config['worker-enabled']:

            hookenv.relation_set(relation_id,
                                 {'operational' : True })
        else:
            
            hookenv.relation_set(relation_id,
                                 {'operational' : False })
        

        relations = hookenv.relations()
        log(str(relations))
    
if __name__ == "__main__":
    # execute a hook based on the name the program is called by
    # In this case, its master-relation-joined
    hooks.execute(sys.argv)
