#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv

def master_relation_joined():
    """
    This hook is called when the unit is up and we can access its
    private-address, but interface data from remote units are not to be
    expected to be available at this stage.

    juju relate master worker
         ->(created)->
                      (joined)->
                                (changed)->

    For our charm, we just access it to do some informative logging.
    """
    hookenv.log(" ========= hook: master-relation-joined  ========")

    relation_id = hookenv.relation_id()

    remoteUnit = os.environ.get('JUJU_REMOTE_UNIT', None) # remote_unit()

    masterAddr = hookenv.relation_get('private-address', unit=remoteUnit)

    hookenv.log(f"Joined with MASTER at private-address: {masterAddr}")

if __name__ == "__main__":
    master_relation_joined()
