#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from hookenv import log

def master_relation_created():
    """
    This hook is called before the remote unit is up and before master-relation-joined.

    #TODO: This hook lacks official documentation.

    juju relate master worker
         ->(created)->
                      (joined)->
                                (changed)->
    """
    log(" ========= hook: master-relation-created  ========")


if __name__ == "__main__":
    master_relation_created()
