#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv

def upgrade_charm():
    hookenv.log('Upgrading charm-master')

if __name__ == "__main__":
    upgrade_charm()