#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from hookenv import log

def install():

    log('Installing charm: master')


if __name__ == "__main__":
    # execute a hook based on the name the program is called by
    install()