#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv
import random

def master_service_relation_created():
    """
    This hook is called before the remote unit is up and before master-relation-joined.

    juju relate master worker
         ->(created)->
                      (joined)->
                                (changed)->
    """
    hookenv.log(" ========= hook: master-service-relation-created  ========")

if __name__ == "__main__":
    master_service_relation_joined()