#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from hookenv import log

def master_application_relation_created():
    """
    [name]-relation-created is run after the install hook and before any [name]-relation-joined hooks.
    It is guaranteed to run before any leadership hook for peer relations.
    For non-peer relations established at a
    later point in time, the hook will fire once the relation has been established.
    """

    log(" ========= hook: master-application-relation-created  ========")

if __name__ == "__main__":
    master_application_relation_created()