#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv
import random

def generateWorkerKey():
    """Return a random key of length 4,
    which will be passed as new workers join."""
    return ''.join(random.choice('0123456789ABCDEF') for i in range(4))

def master_service_relation_joined():
    """
    This hook is called when the unit is up and we can access its
    private-address, but interface data from remote units are not to be
    expected to be available at this stage.
    Its however a good place to start populating the data we want to
    publish to other units joining up to the relation.

    $ juju relate master worker
         ->(created)->
                      (joined)->
                                (changed)->

    Our charm generates a unique key here, based on the remote unit name
    and sets it on the relation.
    """

    hookenv.log(" ========= hook: master-service-relation-joined  ========")

    # Generate a key
    _wk = generateWorkerKey()

    # Get the remote unit name so that we can use that for a composite key.
    remoteUnitName=os.environ['JUJU_REMOTE_UNIT']

    # Assemble the relation data.
    relation_data = { f"{remoteUnitName}-worker-key": _wk }

    # Set the relation data on the relation.
    hookenv.relation_set(hookenv.relation_id(),
                         relation_settings=relation_data )

if __name__ == "__main__":
    master_service_relation_joined()