#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv

def master_service_relation_broken():
    """
    Lets not do anything here now but let the log know we passed through.
    """
    hookenv.log(" ========= hook: master-service-relation-broken  ========")


if __name__ == "__main__":
    master_service_relation_broken()
