#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from hookenv import log, relation_ids, related_units, status_set

def master_application_relation_changed():
    """
    https://discourse.juju.is/t/charm-hooks/1040

    [name]-relation-changed is always run once, after -joined, and will subsequently be run whenever that remote unit
    changes its settings for the relation. It should be the only hook that relies upon remote relation settings from
    relation-get, and it should not error if the settings are incomplete: you can guarantee that when the remote unit
    changes its settings, the hook will be run again.

    The settings that you can get, and that you should set, are determined by the relation’s interface.
    """
    log(" ========= hook: master-application-relation-changed  ========")

    # For the master-application relation, get all relation_ids
    # TODO: dont use the name since we are in a relation
    rel_ids = relation_ids('master-application')

    # Get the first one since we expect to only have one master-application relation.
    master_application_rel_id = rel_ids[0]

    # Get all the related units
    units = related_units(master_application_rel_id)

    # Show how many related units we have.
    status_set("active", f"Related Workers: {len(units)}")
            
if __name__ == "__main__":
    master_application_relation_changed()
