#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv

def master_service_relation_departed():
    relation_id = hookenv.relation_id()
    hookenv.log(f"=========== DEPARTED on relation {relation_id} =============")
    pass

if __name__ == "__main__":
    master_service_relation_departed()
