#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
import hookenv

def master_service_relation_departed():
    """

    """

    hookenv.log(" ========= hook: master-service-relation-departed  ========")

if __name__ == "__main__":
    master_service_relation_departed()
