#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from hookenv import log

def stop():

    log("=========== hook: stop ===========")

if __name__ == "__main__":
    stop()
