#!/usr/bin/env python3
import os
import sys
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from hookenv import log, relation_ids, function_get, relation_set

# This action "broadcasts" a message by setting the message key value on
# the master-application relation. All related worker units picks this up
# via the relation-changed hook.

# If the message don't differ from the previous message, nothing happens since
# the value on the relation remains unchanged.

# $ juju run-action master/0 broadcast-message message="Hello World" --wait

log(" ========= action: broadcase-message  ========")

# Assume that the first relation_id is the only and use that.
relation_id = relation_ids('master-application')[0]

# Get the message from the juju function/action
message = function_get('message')

relation_data = { 'message': message }

# ... set the relational data.
relation_set(relation_id, relation_settings=relation_data)